# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

sudo: false
warnings_are_errors: true

r:
- oldrel
- release
- devel

r_packages:
- covr
- knitr
- pander

r_github_packages:
- hadley/rlang
- tidyverse/dplyr

after_success:
- Rscript -e 'covr::codecov()'
